name = "pick-history"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]
